AWSTemplateFormatVersion: 2010-09-09

Parameters:
  HeadBucket:
    Type: String
  RedirectBucket:
    Type: String

Resources:
  PersonalWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref HeadBucket
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  PersonalWebsiteRedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref RedirectBucket
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: www.codyperakslis.com
          Protocol: https
